import Foundation

// MARK: - ExameModel

/// Represents a medical exam in the system.
/// This is the main entity for the Exames feature following VIPER architecture.
struct ExameModel: Codable, Identifiable, Equatable {
    
    // MARK: - Properties
    
    /// Unique identifier for the exam
    let id: String
    
    /// Name/type of the exam (e.g., "Hemograma Completo", "Raio-X Tórax")
    let nome: String
    
    /// Location where the exam was performed (e.g., "Hospital São Lucas", "Clínica Santa Maria")
    let localRealizado: String
    
    /// Name of the doctor who requested the exam
    let medicoSolicitante: String
    
    /// Reason or complaint that motivated the exam request
    let motivoQueixa: String
    
    /// Date when the exam was registered in the system
    let dataCadastro: Date
    
    /// Optional URL to the exam file/document stored in Firebase Storage
    /// Example: "exames/user123/hemograma_2024.pdf"
    let urlArquivo: String?
    
    // MARK: - Computed Properties
    
    /// Returns a formatted date string for display purposes
    var dataFormatada: String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .none
        formatter.locale = Locale(identifier: "pt_BR")
        return formatter.string(from: dataCadastro)
    }
    
    /// Returns true if the exam has an associated file
    var temArquivo: Bool {
        return urlArquivo != nil && !(urlArquivo?.isEmpty ?? true)
    }
    
    /// Returns a short summary of the exam for preview
    var resumo: String {
        return "\(nome) - \(localRealizado)"
    }
    
    // MARK: - Initializer
    
    /// Creates a new ExameModel instance
    /// - Parameters:
    ///   - id: Unique identifier (usually generated by Firebase)
    ///   - nome: Name/type of the exam
    ///   - localRealizado: Location where exam was performed
    ///   - medicoSolicitante: Requesting doctor's name
    ///   - motivoQueixa: Reason for the exam
    ///   - dataCadastro: Registration date (defaults to current date)
    ///   - urlArquivo: Optional URL to exam file
    init(
        id: String = UUID().uuidString,
        nome: String,
        localRealizado: String,
        medicoSolicitante: String,
        motivoQueixa: String,
        dataCadastro: Date = Date(),
        urlArquivo: String? = nil
    ) {
        self.id = id
        self.nome = nome
        self.localRealizado = localRealizado
        self.medicoSolicitante = medicoSolicitante
        self.motivoQueixa = motivoQueixa
        self.dataCadastro = dataCadastro
        self.urlArquivo = urlArquivo
    }
    
    // MARK: - Coding Keys
    
    /// Custom coding keys for Firebase Firestore compatibility
    enum CodingKeys: String, CodingKey {
        case id
        case nome
        case localRealizado = "local_realizado"
        case medicoSolicitante = "medico_solicitante"
        case motivoQueixa = "motivo_queixa"
        case dataCadastro = "data_cadastro"
        case urlArquivo = "url_arquivo"
    }
}

// MARK: - ExameModel + Mock Data

extension ExameModel {
    /// Creates mock data for testing and preview purposes
    static func mock() -> ExameModel {
        return ExameModel(
            id: "123e4567-e89b-12d3-a456-426614174000",
            nome: "Hemograma Completo",
            localRealizado: "Hospital São Lucas",
            medicoSolicitante: "Dr. João Silva",
            motivoQueixa: "Rotina anual",
            dataCadastro: Date(),
            urlArquivo: "exames/user123/hemograma_2024.pdf"
        )
    }
    
    /// Creates an array of mock data for testing lists
    static func mockList() -> [ExameModel] {
        return [
            ExameModel(
                id: "1",
                nome: "Hemograma Completo",
                localRealizado: "Hospital São Lucas",
                medicoSolicitante: "Dr. João Silva",
                motivoQueixa: "Rotina anual",
                dataCadastro: Date().addingTimeInterval(-86400 * 7), // 7 days ago
                urlArquivo: "exames/user123/hemograma_2024.pdf"
            ),
            ExameModel(
                id: "2",
                nome: "Raio-X Tórax",
                localRealizado: "Clínica Santa Maria",
                medicoSolicitante: "Dra. Maria Santos",
                motivoQueixa: "Dor no peito",
                dataCadastro: Date().addingTimeInterval(-86400 * 3), // 3 days ago
                urlArquivo: "exames/user123/raio_x_2024.pdf"
            ),
            ExameModel(
                id: "3",
                nome: "Ressonância Magnética",
                localRealizado: "Hospital Central",
                medicoSolicitante: "Dr. Pedro Costa",
                motivoQueixa: "Investigação neurológica",
                dataCadastro: Date().addingTimeInterval(-86400 * 1), // 1 day ago
                urlArquivo: nil
            ),
            ExameModel(
                id: "4",
                nome: "Exame de Sangue",
                localRealizado: "Laboratório Lab+",
                medicoSolicitante: "Dr. Carlos Lima",
                motivoQueixa: "Check-up preventivo",
                dataCadastro: Date(),
                urlArquivo: "exames/user123/sangue_2024.pdf"
            )
        ]
    }
}

// MARK: - ExameModel + Validation

extension ExameModel {
    /// Validates if the model has all required fields filled
    /// - Returns: True if valid, false otherwise
    func isValid() -> Bool {
        return !nome.isEmpty &&
               !localRealizado.isEmpty &&
               !medicoSolicitante.isEmpty &&
               !motivoQueixa.isEmpty
    }
    
    /// Returns validation errors as an array of strings
    /// - Returns: Array of error messages (empty if valid)
    func validationErrors() -> [String] {
        var errors: [String] = []
        
        if nome.isEmpty {
            errors.append("Nome do exame é obrigatório")
        }
        
        if localRealizado.isEmpty {
            errors.append("Local realizado é obrigatório")
        }
        
        if medicoSolicitante.isEmpty {
            errors.append("Médico solicitante é obrigatório")
        }
        
        if motivoQueixa.isEmpty {
            errors.append("Motivo/queixa é obrigatório")
        }
        
        return errors
    }
}

// MARK: - ExameModel + Firebase

extension ExameModel {
    /// Converts the model to a dictionary for Firebase Firestore
    /// - Returns: Dictionary representation compatible with Firestore
    func toFirestoreDictionary() -> [String: Any] {
        var dict: [String: Any] = [
            CodingKeys.id.rawValue: id,
            CodingKeys.nome.rawValue: nome,
            CodingKeys.localRealizado.rawValue: localRealizado,
            CodingKeys.medicoSolicitante.rawValue: medicoSolicitante,
            CodingKeys.motivoQueixa.rawValue: motivoQueixa,
            CodingKeys.dataCadastro.rawValue: dataCadastro
        ]
        
        if let url = urlArquivo {
            dict[CodingKeys.urlArquivo.rawValue] = url
        }
        
        return dict
    }
    
    /// Creates an ExameModel from a Firestore dictionary
    /// - Parameter dictionary: Dictionary from Firestore
    /// - Returns: ExameModel instance or nil if parsing fails
    static func fromFirestoreDictionary(_ dictionary: [String: Any]) -> ExameModel? {
        guard
            let id = dictionary[CodingKeys.id.rawValue] as? String,
            let nome = dictionary[CodingKeys.nome.rawValue] as? String,
            let localRealizado = dictionary[CodingKeys.localRealizado.rawValue] as? String,
            let medicoSolicitante = dictionary[CodingKeys.medicoSolicitante.rawValue] as? String,
            let motivoQueixa = dictionary[CodingKeys.motivoQueixa.rawValue] as? String,
            let dataCadastro = dictionary[CodingKeys.dataCadastro.rawValue] as? Date
        else {
            return nil
        }
        
        let urlArquivo = dictionary[CodingKeys.urlArquivo.rawValue] as? String
        
        return ExameModel(
            id: id,
            nome: nome,
            localRealizado: localRealizado,
            medicoSolicitante: medicoSolicitante,
            motivoQueixa: motivoQueixa,
            dataCadastro: dataCadastro,
            urlArquivo: urlArquivo
        )
    }
}

